version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network

  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
