version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"

    environment:
      DB_HOST: postgres
      DB_NAME: mydb
      DB_USE: myusr
      DB_PASSWORD: mypassword
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my-networks

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 5s
      retries: 5
    networks:
      - my-networks

volumes:
  pgdata:

networks:
  my-networks:
